import matplotlib.pyplot as plt
from sklearn.decomposition import PCA



def plot_segment_customers(segment_summary, output_path=None):
    """
    Plot the number of customers in each RFM segment.

    Parameters
    ----------
    segment_summary : pandas.DataFrame
        Segment-level summary statistics.
    output_path : str, optional
        Path to save the figure.
    """

    plt.figure(figsize=(9, 5))

    plt.bar(
        segment_summary["Segment"],
        segment_summary["Customers"],
    )

    plt.title("Customers by RFM Segment")
    plt.xlabel("Customer Segment")
    plt.ylabel("Number of Customers")

    plt.xticks(rotation=20)
    plt.tight_layout()

    if output_path:
        plt.savefig(output_path, dpi=300)

    plt.show()


def plot_segment_revenue(segment_summary, output_path=None):
    """
    Plot total revenue generated by each RFM segment.

    Parameters
    ----------
    segment_summary : pandas.DataFrame
        Segment-level summary statistics.
    output_path : str, optional
        Path to save the figure.
    """

    plt.figure(figsize=(9, 5))

    plt.bar(
        segment_summary["Segment"],
        segment_summary["TotalRevenue"],
    )

    plt.title("Revenue by RFM Segment")
    plt.xlabel("Customer Segment")
    plt.ylabel("Total Revenue")

    plt.xticks(rotation=20)
    plt.tight_layout()

    if output_path:
        plt.savefig(output_path, dpi=300)

    plt.show()



def plot_kmeans_evaluation(
    cluster_evaluation,
    output_path=None,
):
    """
    Plot K-Means inertia and silhouette scores.

    Parameters
    ----------
    cluster_evaluation : pandas.DataFrame
        Output from evaluate_kmeans().
    output_path : str, optional
        Path to save the figure.
    """

    fig, ax1 = plt.subplots(figsize=(9, 5))

    ax1.plot(
        cluster_evaluation["K"],
        cluster_evaluation["Inertia"],
        marker="o",
    )

    ax1.set_xlabel("Number of Clusters (K)")
    ax1.set_ylabel("Inertia")
    ax1.set_xticks(cluster_evaluation["K"])

    ax2 = ax1.twinx()

    ax2.plot(
        cluster_evaluation["K"],
        cluster_evaluation["SilhouetteScore"],
        marker="o",
    )

    ax2.set_ylabel("Silhouette Score")

    plt.title("K-Means Cluster Evaluation")
    fig.tight_layout()

    if output_path:
        plt.savefig(output_path, dpi=300)

    plt.show()



def plot_clusters_pca(
    scaled_rfm,
    cluster_labels,
    output_path=None,
):
    """
    Visualize K-Means clusters using PCA.
    """

    pca = PCA(n_components=2)

    components = pca.fit_transform(scaled_rfm)

    plt.figure(figsize=(9, 6))

    for cluster in sorted(set(cluster_labels)):
        mask = cluster_labels == cluster

        plt.scatter(
            components[mask, 0],
            components[mask, 1],
            label=f"Cluster {cluster}",
            alpha=0.6,
        )

    plt.title("K-Means Customer Clusters — PCA Visualization")
    plt.xlabel("Principal Component 1")
    plt.ylabel("Principal Component 2")
    plt.legend()

    plt.tight_layout()

    if output_path:
        plt.savefig(output_path, dpi=300)

    plt.show()