[project]
name = "cli-memory-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "openai>=3.19.2",
]

[project.scripts]
cli-memory-chatbot = "cli_memory_chatbot:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
